### ISSUE TITLE
Update mdast to remark

### ISSUE THREAD

**Issue by wooorm** [mapbox/mdast-react#13]
Hey @tmcw / mapbox!

I’d like to update mdast to remark. You’ve probably noticed this, but mdast got a big new update including a rename to remark ([see what’s new](https://github.com/wooorm/remark/releases/tag/3.0.0), learn [how to upgrade plugins](https://github.com/wooorm/remark/blob/master/doc/plugins.md#renaming-from-mdast-to-remark)).

I have time to do the update myself if needed, but I’d first like to know whether you’d like to include GH-11, GH-12 first (as the update will probably make rebasing those more difficult).

**Comment by tmcw** [comment]
:+1: done in 1.1.0

**Comment by wooorm** [comment]
Great work! 👏👏
