### ISSUE TITLE
Is this compatible with remark 4?

### ISSUE THREAD

**Issue by bebraw** [mapbox/mdast-react#15]
I just tried to update a boilerplate of mine to use the newly released remark 4. For some reason it didn't process correctly there (output remained as markdown). Is remark-react compatible with it?

**Comment by wooorm** [comment]
No, it’s not. The section on “What plug-in authors should do” in the release notes for [4.0.0](https://github.com/wooorm/remark/releases/tag/4.0.0) might help, if you’re willing to write a PR, though!

**Comment by AlastairTaft** [comment]
I've had a read of the "What plug-in authors should do" but I don't think I know enough about how remark works yet to have a go at a pull request. Got any more pointers? Or is this on the roadmap for an upgrade in the future?
