### ISSUE TITLE
Handling ID attributes?

### ISSUE THREAD

**Issue by ben-eb** [mapbox/mdast-react#19]
Thanks for the module. 👍

I was wondering if it would be possible for remark-react to handle the `id` attribute, so that it can be used alongside plugins such as https://github.com/wooorm/remark-slug & https://github.com/ben-eb/remark-autolink-headings. Right now, I have to use `dangerouslySetInnerHTML` so that I can work around this issue, but would much prefer that it would be handled here.

**Comment by tmcw** [comment]
Main concern here is [DOM Clobbering](http://www.thespanner.co.uk/2013/05/16/dom-clobbering/), which is a very possible attack if we accept user-submitted IDs. If we support IDs they'll likely have to be prefixed to be safe.

**Comment by ben-eb** [comment]
What do you think about an off-by-default flag for this behaviour? In my case, the input is not coming from the end-user; I'm building a site using https://github.com/MoOx/phenomic and so I can trust myself to not clobber the DOM. 😄

**Comment by BarryThePenguin** [comment]
This would help when working with https://github.com/wooorm/remark-toc too

**Comment by wooorm** [comment]
id attributes are allowed according to the current schema, but as they can “clobber” the DOM, they’re prefixed by default. In the schema, remove id from the `schema.clobber` array!
