### ISSUE TITLE
TypeError: No default value

### ISSUE THREAD

**Issue by OKNoah** [mapbox/mdast-react#24]
When using an earlier version, I was having the issue where `<` symbols would show up as `&lt;`. I updated to `3.0.1` but got issues there. 

```
MIDDLEWARE ERROR:
Error: mdast-util-definitions expected node — index.js:53
["loginPage/USER_FETCH", "loginPage/USER_FETCH_SUCCESS", "loginPage/USER_FETCH_FAILURE"] 
```

I took this to be because `remark` was version `4.2.0`so I updated that to `5.0.1`. Now I get errors like this:

```
MIDDLEWARE ERROR:
TypeError: No default value — traverseAllChildren.js:157
["loginPage/USER_FETCH", "loginPage/USER_FETCH_SUCCESS", "loginPage/USER_FETCH_FAILURE"]
```

**Comment by wooorm** [comment]
Hi @OKNoah! What version of React are you using? I couldn’t find much, other than that it’s maybe `input` related?

**Comment by OKNoah** [comment]
@wooorm The updating stuff aside, I think there is a bug with `<` and `>` within backticks.

Here is the input and the output from the console.

![screen shot 2016-07-27 at 4 14 37 pm](https://cloud.githubusercontent.com/assets/3739277/17195904/92b03374-5415-11e6-9325-4e11867b2c00.png)
![screen shot 2016-07-27 at 4 14 17 pm](https://cloud.githubusercontent.com/assets/3739277/17195909/97779618-5415-11e6-9c12-6726ec0d2db7.png)

This is the issue (and commit) that I thought might resolve the problem, but I think I was mistaken about what version it was introduced in, which is why I was trying to update everything: https://github.com/mapbox/remark-react/issues/3

**Comment by OKNoah** [comment]
Looks like this is fixed in an update. After adding `.contents` after `.process()` everything seems to work. I don't see that in the README though.
