### ISSUE TITLE
Break the fork: allow searching for `remark-react`

### ISSUE THREAD

**Issue by wooorm** [mapbox/mdast-react#29]
As this project is a fork, GH doesn’t show it in search results! 😬

**Comment by wooorm** [comment]
Ah darn, that would of clear the [issue tracker](http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository) too.

**Comment by tmcw** [comment]
👍 I'll contact GitHub support, they can break forks without killing issue trackers, afaik.

**Comment by wooorm** [comment]
Ooh, TIL!

**Comment by tmcw** [comment]
Done!

**Comment by wooorm** [comment]
Perfect!
