### ISSUE TITLE
avoid double-escaping special characters

### ISSUE THREAD

**Issue by lukebaker** [mapbox/mdast-react#3]
Example used on demo https://www.mapbox.com/mdast-react/:

```
console.log('&, <, >, ", \', and `');
```

results in:

```
console.log(&apos;&amp;, &lt;, &gt;, &quot;, \&apos;, and &grave;&apos;);
```

**Comment by tmcw** [comment]
Fixed in a13fd4b252050b5aa2e5f61d7671caf4a6b9cd8b - need to scope out possible other cases of double-encoding

**Comment by lukebaker** [comment]
Looking good. Thanks!

**Comment by bebraw** [comment]
@lukebaker Safe to close?

**Comment by lukebaker** [comment]
@bebraw, yep!
