### ISSUE TITLE
breaking change in 3.1.1

### ISSUE THREAD

**Issue by BarryThePenguin** [mapbox/mdast-react#37]
Just an FYI, the update to support remark@7.0.0 should have been released as a major version bump.

Sorry I don't have any suggestions on how to proceed..

**Comment by tmcw** [comment]
Thanks - my bad, I've released 3.0.0, a breaking change, and deprecated the incorrectly breaking versions.

**Comment by BarryThePenguin** [comment]
Awesome :tada:

**Comment by wooorm** [comment]
Sorry about that, I forgot to note that it should be a major bump!
