### ISSUE TITLE
remark-react does not render telephone links

### ISSUE THREAD

**Issue by rmtsrc** [mapbox/mdast-react#38]
[`remark-react`](https://github.com/mapbox/remark-react) does not render telephone links.

### Input

```
[telephone link](tel:1234567890)
```

### Expected output

```
<a href="tel:1234567890">telephone link</a>
```

### Actual output

```
<a>telephone link</a>
```

### Steps to reproduce

1. `git clone git@github.com:sebflipper/remark-test.git`
2. `cd remark-test`
3. `yarn` - installs modules
4. `yarn remark-test` - shows the correct output from a basic stand-alone [`remark`](https://github.com/wooorm/remark) setup.
5. `yarn start` - starts a React server with the same Markdown text, with the incorrectly rendered telephone link.

**Comment by wooorm** [comment]
It doesn’t by default (potentially dangerous?), but you can configure it to do so by specifying which things are allowed!

You can see the docs for the `sanitize` settings her: https://github.com/mapbox/remark-react#configuration, which in turn links to [this schema documentation](https://github.com/syntax-tree/hast-util-sanitize#schema)

Let me know if it works!

**Comment by rmtsrc** [comment]
Thanks that's fix it! 🎉 

For future reference I extended the default schema and added the `tel` protocol via:

```js
import ghSchema from 'hast-util-sanitize/lib/github';

const schema = { ...ghSchema };
schema.protocols.href.push('tel');

const markdownOptions = { sanitize: schema };
remark().use(reactRenderer, markdownOptions).processSync(body).contents;
```

**Comment by wooorm** [comment]
Great! :+1:

Be careful, though, I don’t think `{ ...ghSchema }` makes a deep copy, so `protocols` is also modified in the original schema (which probably won’t cause problems as you’re most likely to use it once)!

**Comment by rmtsrc** [comment]
Good spot, I've checked it and it was modifying the original, so I've changed it to use lodash's: `cloneDeep`, which doesn't tamper with the original value.
