### ISSUE TITLE
Using remark-react in a tab nature causes DOM related errors

### ISSUE THREAD

**Issue by kand617** [mapbox/mdast-react#40]
I am using this remark-react to render markdown inside a tab like environment.
Based on the active tab, a content container is passed markdown as props which is inturn passed to remark-react...
```
const item = remark().use(reactRenderer).processSync(this.props.md).contents;
    return (<div>
      {item}
    </div>);
```

The errors I am seeing when changing tabs quickly:

![image](https://cloud.githubusercontent.com/assets/5092518/25474164/4bae846e-2b86-11e7-8c7b-1852b673236c.png)

Should I be caching the result call to remark?

Environment details
"react": "^15.5.4",
"react-dom": "^15.5.4",
"remark": "^7.0.0",
"remark-react": "^4.0.0",
 "styled-components": "^1.4.5"

**Comment by davidtheclark** [comment]
@kand617: I'm not sure we're going to be able to help you debug this without a simplified test case. Any number of things could be going wrong in your screenshot ¯\_(ツ)_/¯. Can you try to isolate the error and reduce the amount of complexity in the example?

**Comment by kand617** [comment]
Hi @davidtheclark ,

You are right, 
And I have isolated the logic in to a simple app. 

https://github.com/kand617/react-webpack-babel/commit/8aa730c57b6ff9733f80d13fb804291e4a890209

The app reads 2 markdown files, when the toggle button is clicked repeatedly, you will see the errors and strange behavior.

**Comment by kand617** [comment]
@davidtheclark 

Looks like I found a solution. 
When rendering the contents, it appears that if I give a unique key to the container element, DOM nodes are correctly manipulated. 

```
  const item = remark().use(reactRenderer, options).processSync(md).contents;
    return (<div key={Date.now()}>
      {item}
    </div>);
```
