### ISSUE TITLE
I can't use tasks list like github

### ISSUE THREAD

**Issue by sosukesuzuki** [mapbox/mdast-react#44]
I want to use tasks list like below:
- [ ] first task
- [ ] second task

I thought `remark-react` correspond to GFM. But, when I use tasks list, a normal list was output instead of a checkbox.

**Comment by wooorm** [comment]
remark-react is safe by default, so you’ll need to specify a [sanitation schema in configuration](https://github.com/mapbox/remark-react#configuration), or pass `sanitize: false`!

**Comment by sosukesuzuki** [comment]
Thanks for telling me it, @wooorm ! I can use tasks list. I will continue to use `remark-react` from now on!

**Comment by wooorm** [comment]
Perfect!

**Comment by domharrington** [comment]
For anyone who comes across this problem in future, I documented my solution here: https://github.com/syntax-tree/hast-util-sanitize/pull/2#issuecomment-400043867
