### ISSUE TITLE
HTML in markdown always getting escaped

### ISSUE THREAD

**Issue by zsherman** [mapbox/mdast-react#45]
Have a feeling I could be missing something very obvious here so apologies if this has already been addressed, but any markup in my markdown seems to be getting escaped with no way to override this behavior. I've tried modifying the sanitization options as well as the `toHast` options but to no avail. As far as I can tell this doesn't work in the `remark-react` demo either. Something like:

```
<h2>Testing</h2>
```

gets converted to:

```
\u003ch2\u003eTesting!\u003c/h2\u003e\
```

Could someone point me in the right direction here?

**Comment by wooorm** [comment]
Hi @zsherman, welcome!

The (main?) reason to use `remark-react` is to create React elements from markdown without resorting to `dangerouslySetInnerHTML`, as that’s a potentially hazardous safety concern.

There’s no way to do this perfectly, that I know of, but there’s three alternative solutions that may help:

1. Use [`remark-html`](https://github.com/wooorm/remark-html) instead, it allows compiling to HTML, then you can `dangerouslySetInnerHTML` the result
2. Use [`markdown-to-jsx`](https://github.com/probablyup/markdown-to-jsx), it has some smart things to parse some basic HTML
3. Use [`remark-rehype`](https://github.com/wooorm/remark-rehype), [`rehype-raw`](https://github.com/wooorm/rehype-raw), and [`rehype-react`](https://github.com/rhysd/rehype-react). This creates React’s virtual dom just like a browser does, so it’s very powerful, but the downside is that it contains an HTML parser (which is huge, of course).

Those are all built on the remark/rehype ecosystem. I don’t know about better solutions outside that ecosystem, but YMMV.

Hope this helps!
Titus

**Comment by zsherman** [comment]
@wooorm thanks for the thorough response! Just tried `markdown-to-jsx` and that did the trick 👍
