### ISSUE TITLE
ReactElement key differs on server and client renders

### ISSUE THREAD

**Issue by ciaranw** [mapbox/mdast-react#5]
I'm using mdast-react in an isomorphic react app. I'm getting warnings from React on the client about the server-generated markup differing from what the client generated. I've tracked this down to the fact that the key counter used in [h.js](https://github.com/mapbox/mdast-react/blob/c9b0ccaf67b94ef976ca184624f5334706473e7c/lib/h.js#L6) resets on every client render, but persists on the server renders. This leads to the counter increasing with every subsequent server render, which causes React to generate non-matching data-reactid attributes on elements.

A potential solution to this might be to initialise a counter in the Compiler constructor, and then use that to source the key from. Quite happy to submit a pull request but thought I should check in case you have a cleaner/better solution?

**Comment by tmcw** [comment]
> A potential solution to this might be to initialise a counter in the Compiler constructor, and then use that to source the key from.

:+1: yep, this sounds like the right path.

**Comment by bebraw** [comment]
I guess this is safe to close given #6 was merged.

**Comment by wooorm** [comment]
Yup, should be fixed!
