### ISSUE TITLE
Pass `position` into props

### ISSUE THREAD

**Issue by s-panferov** [mapbox/mdast-react#50]
Hello. I'm trying to implement two-panel view and to achieve good scrolling and navigation experience I'd like to use `position` information from MDAST. But it seems that react children have no access to an original `Position` structure.

Is it possible to add this functionality?

**Comment by davidtheclark** [comment]
This is another good use case for a more flexible custom components API. Let's think about this as part of the request in https://github.com/mapbox/remark-react/issues/48.
