### ISSUE TITLE
is "remark-react looks for an attributes object on each node" working?

### ISSUE THREAD

**Issue by ruifortes** [mapbox/mdast-react#53]
The docs say "remark-react looks for an attributes object on each node it compiles and adds the found properties as HTML attributes"
I added an attributes object to mdAst nodes but nothing happened.
What the documentation referring to?

**Comment by wooorm** [comment]
Oh I believe that should be hproperties nowadays: https://github.com/syntax-tree/mdast-util-to-hast#hproperties

**Comment by davidtheclark** [comment]
@ruifortes: PR welcome for any additional documentation that would help with your use case 👍

**Comment by wooorm** [comment]
Fixed in the recent makeover. Sorry about the long wait.
