### ISSUE TITLE
remarkReactComponents target classes

### ISSUE THREAD

**Issue by aiwatko** [mapbox/mdast-react#55]
Is it possible to target an element with a class i.e. `div.custom-block` in remarkReactComponents option?
I use `remark-custom-blocks` plugin that creates divs out of markdown, i.e. `[[section]]` --> `div.custom-block.section`. I would like to transform such divs into customised components.
Thanks!

**Comment by wooorm** [comment]
@aiwatko Not really, but maybe you can create a component that either returns the normal div, or your custom components?

**Comment by wooorm** [comment]
I suggest using either components or a remark plugin.
