### ISSUE TITLE
Incorrect treatment of 'tel'-links

### ISSUE THREAD

**Issue by oscarnylander** [mapbox/mdast-react#56]
I realize that this is probably the wrong repository to report this issue in, but I'm a bit lost on where to go to actually solve it.

Basically the problem I have is that a link on the form `[+15553485](tel:+15553485)` generates the following html: `<a>+15553485</a>` instead of the expected `<a href="tel:+15553485">+15553485</a>`.

**Comment by davidtheclark** [comment]
Hi @hedvigoscar. As you suspected, this is a matter for remark itself. If you do open an issue in that repo, I'd urge you to bring some links demonstrating that this is indeed what a Markdown parser is expected to do.

**Comment by wooorm** [comment]
[See `protocols` in `hast-util-sanitize`](https://github.com/syntax-tree/hast-util-sanitize#protocols)!
