### ISSUE TITLE
Test passing options to toHast() wrong?

### ISSUE THREAD

**Issue by stefanprobst** [mapbox/mdast-react#58]
I believe the [test for passing options to `toHast()`](https://github.com/mapbox/remark-react/blob/427840620cb74f41964118b125008efbc9d8fe65/test/index.js#L148) actually does not test anything, since (i) the markdown sample does not contain any html for `allowDangerousHTML` to make a difference, and (ii) AFAICT if `allowDangerousHTML` is set, `toHast` will return `raw` nodes which will be ignored by `hast-to-hyperscript` anyway and thus not show up in the rendered markup.

**Comment by wooorm** [comment]
You‘re right! Thanks!
