### ISSUE TITLE
Laguage type not being passed

### ISSUE THREAD

**Issue by alesanchezr** [mapbox/mdast-react#59]
Let's suppose that the original markdown was a code-block with ```js as opening syntax.

The remarkReactComponents property is not passing the language to the "code" component that y specified, the only property that the component received is an array of children.
```jsx
        {remark().use(reactRenderer, {
          remarkReactComponents: {
            code: PrismCode
          }
        }).processSync(readme).contents}
```
My component `PrismCode` is only receiving the children prop, how can I know that language was this code block defined on?

**Comment by nrhirani** [comment]
Please refer to the comment in the issue -
https://github.com/mapbox/remark-react/issues/23#issuecomment-232691433

You need to pass `{sanitize: {attributes: {'*': ['className']}}}` to get it working in the `remark().use()` function.

Hope that helps :)

**Comment by alesanchezr** [comment]
Thank you @nrhirani !
