### ISSUE TITLE
5.0.0

### ISSUE THREAD

**Issue by wooorm** [mapbox/mdast-react#60]
Heya! I’ve just pushed some polishing, updating, and cleaning stuff. Would be nice to cut a new release, but I don’t have permissions.

@davidtheclark Could you publish a major for me?

Also: maybe we can move this to @remarkjs for better maintainability.

Cheers 🎉

**Comment by davidtheclark** [comment]
@wooorm I added you as an npm collaborator. I wasn't sure whether you wanted me to release the latest 4.x.x version in the releases changelog or a new 5.0.0 version as this issue indicates? You could do it yourself or fill me in on the details 👍 

I think it's a good idea to move this to @remarkjs. I need to verify whether I can transfer this repo or if we'll need you to create a new repo/fork and go from there (we'd just put a warning & link in this readme). If you'd like to go that route (create a new repo/fork), I think you could do that whenever you feel like it. And meanwhile I'll look into the transfer.

**Comment by wooorm** [comment]
@davidtheclark done, released as 5.0.0! 🎉

> I think it's a good idea to move this to @remarkjs. I need to verify whether I can transfer this repo or if we'll need you to create a new repo/fork and go from there (we'd just put a warning & link in this readme). If you'd like to go that route (create a new repo/fork), I think you could do that whenever you feel like it. And meanwhile I'll look into the transfer.

I’m fine waiting for a confirmation. I guess this is a thing for Mapbox’s legal department: moving the repo would still support existing links and redirect them.

We can have the repo here as well, but it’s simpler for remarkjs and maintainers attached to that to help support it from there.

Whatever works for y’all!

**Comment by agius** [comment]
@wooorm Hiya! I tried to transfer the repo today, but I can only transfer it to organizations where I can create repositories. So I thought we should do one of:

1. Add you or another member of the RemarkJS team as an admin collaborator on this repo, and that person can transfer from Mapbox to RemarkJS
2. Transfer the repo to your personal Github account (or another RemarkJS member), and then you can transfer from your account to the org
3. Someone could temporarily add me to the RemarkJS org, I can transfer the repo, then be removed

Which of those sound best? Thanks!

**Comment by wooorm** [comment]
@agius Hey awesome, sweet!

1 is fine 👍 Who wants to remain on as an outside collaborator? @davidtheclark? Any other requests from Mapbox?

**Comment by davidtheclark** [comment]
@wooorm I just made you an admin of the repo, so you should be able to take it from here. 

Please keep me on as an outside collaborator 👍

**Comment by wooorm** [comment]
Hmm, that still doesn’t work for me!

<img width="757" alt="screenshot 2018-12-15 at 22 34 00" src="https://user-images.githubusercontent.com/944406/50047627-88779980-00b9-11e9-83f1-d8d6a03c6bbb.png">

@davidtheclark I’ve added you to @remarkjs temporarily, are you able to do this?
When this works, I’ll remove you again, and add you as an outside collaborator!

**Comment by davidtheclark** [comment]
I can't do it, either.

@wooorm You could add @agius to the remarkjs org. Or @agius you could transfer the repo to @wooorm. I bet one of those will work. 😬

**Comment by agius** [comment]
@davidtheclark welp, I tried to transfer to @wooorm and I got this:

<img width="1001" alt="screen shot 2018-12-17 at 8 17 00 am" src="https://user-images.githubusercontent.com/162151/50101409-7b50cc80-01d7-11e9-8574-2a2ed176740f.png">

😕 I am not confident that if I transfer the repo to myself I will then be able to transfer it along to @wooorm afterwards. Looks like we're down to:

1. temporarily add me to remarkjs org (I'd give it... 50/50 odds of working?)
2. I can open ticket with Github support (will probably need to CC in @wooorm / remarkjs team)

**Comment by wooorm** [comment]
I think you’re able to transfer from one user to me a bit more easily, so I’d say try that?
Otherwise I’ll try 1. and you could also do 2. CC is fine.
Weird how it’s so hard haha :p Thanks for keeping with it you two!

**Comment by agius** [comment]
> @wooorm I think you’re able to transfer from one user to me a bit more easily, so I’d say try that?

My concerns here are:

1. If I can't transfer from my personal account to your personal account for some reason, then I'm kinda "stuck" as the only owner for this repo, instead of all owners of the Mapbox Github org. 🚌 factor = 1 until Github support can sort it out
2. Not sure how Github handles things on the backend, but seems like a much higher chance of things going wrong with 4 redirects ( `mapbox/remark-react` → `agius/remark-react` → `wooorm/remark-react` → `remarkjs/remark-react` ) than with just one transfer

My preference would be to try 1 (please add me to remarkjs , then remove me once transferred). Then if that fails, move on to 2 (Github support). If y'all are uncomfortable with 1, then we can go straight to 2. 

I'd be less worried about using personal accounts if Github hadn't already demonstrated several unexpected edge cases. Just feels too probable that _something_ unexpected will happen with the ownership chain (i.e. "you cannot transfer this repo at this time" ; "you can only transfer a repo once" ; etc) and this will drag out further. Thanks for your patience, sorry this turned out to be much more difficult than any of us thought.

**Comment by wooorm** [comment]
OK invite sent! I hope you have enough rights on remarkjs now, if you also need admin rights for some reason we can try that too!

> If I can't transfer from my personal account to your personal account for some reason, then I'm kinda "stuck" as the only owner for this repo, instead of all owners of the Mapbox Github org. 🚌 factor = 1 until Github support can sort it out

In my experience GH is super chill about transferring repo’s from one person to another, I think org to org as we’re doing here is much more involved.

> Not sure how Github handles things on the backend, but seems like a much higher chance of things going wrong with 4 redirects ( mapbox/remark-react → agius/remark-react → wooorm/remark-react → remarkjs/remark-react ) than with just one transfer

I believe they just support all the old links, I’ve moved some stuff through several names and usernames and I think they just keep the “old” references as redirects until something new exists there.

> Thanks for your patience, sorry this turned out to be much more difficult than any of us thought.

Hey don’t worry about it, thanks *you*, and yes darn it’s difficult lol

**Comment by agius** [comment]
@wooorm done! 🎉 I've left the `remarkjs` org. Thanks for the help!

**Comment by wooorm** [comment]
Thanks @agius and @davidtheclark. Even npm was done. I really appreciate you two taking the time. 🎉
