### ISSUE TITLE
Uncaught TypeError: information is not a function

### ISSUE THREAD

**Issue by TylerBarnes** [mapbox/mdast-react#61]
When I follow the instructions in the readme I get this error. Do I need to include anything else?

**Comment by wooorm** [comment]
Could you try the newly released 5.0.0?

**Comment by TylerBarnes** [comment]
For sure, I'll give it a shot when I get home tonight

**Comment by wooorm** [comment]
@TylerBarnes Let us know when you finally get home, getting worried here! 😉
Closing for now, but please respond if this is still an issue!

**Comment by TylerBarnes** [comment]
Ha! 🤣 You can rest easy, I finally made it home!
I did end up going the dangerouslySetInnerHtml route though for the project I was working on. If I refactor or need to set another project up with something similar I'll come back and let you know if it's still an issue.
Thanks for your help and for your work though!
