### ISSUE TITLE
table rendering not working

### ISSUE THREAD

**Issue by Ognian** [mapbox/mdast-react#64]
Hello,
by using the code from the read.me:
```
const res = remark()
    .use(remark2react)
    .processSync(value)
```

and using this simple markdown -> value:`P1|P2|P3| P4| P5| P6| P7| P8|↵---|---|---|---|---|---|---|---|↵XX1| XX2|XX3|XX4|XX5|XX6|XX7|XX8`

leads to
![image](https://user-images.githubusercontent.com/1231174/56125217-b9d57880-5f78-11e9-8401-d55a8a6c491f.png)

which is wrong since the "new lines" are not sanitised and this leads in the end to:
![image](https://user-images.githubusercontent.com/1231174/56125450-39fbde00-5f79-11e9-9828-93db2ca4e497.png)

Any idea how to fix this?
Thanks a lot Ognian

PS: children 0,2 and 4 should be omitted

**Comment by ChristianMurphy** [comment]
@Ognian in the example

```md
P1|P2|P3| P4| P5| P6| P7| P8|↵---|---|---|---|---|---|---|---|↵XX1| XX2|XX3|XX4|XX5|XX6|XX7|XX8
```

it appears that `U+21B5 : DOWNWARDS ARROW WITH CORNER LEFTWARDS` is being used, use newlines or carriage returns instead.
Also ensure both the opening and closing of a row are fenced with `|`.

E.G.

```md
|P1 |P2 |P3 |P4 |P5 |P6 |P7 |P8 |
|---|---|---|---|---|---|---|---|
|XX1|XX2|XX3|XX4|XX5|XX6|XX7|XX8|
```

**Comment by Ognian** [comment]
Thanks for the quick reply, but unfortunately I pasted in the issue the value text from chrome debugger, where LF (ASCII 10 ) is displayed with `U+21B5 : DOWNWARDS ARROW WITH CORNER LEFTWARDS `...
So the easiest way to reproduce is:
```
const res = remark()
    .use(remark2react)
    .processSync("|a|b|\n" +
      "|---|---|\n" +
      "|c|d|")
```
and inspect res.contents

PS: I did a code sandbox https://codesandbox.io/s/zz9wo4jv93

**Comment by ChristianMurphy** [comment]
:thinking: not seeing the same issue with `remark-rehype`, this may be more specific to `remark-react`
https://runkit.com/christianmurphy/remark-table-parse

**Comment by Ognian** [comment]
I need react, so I tried `remark-rehype`and `rehype-react` leading to the **same** problem...
https://codesandbox.io/s/v30px4q3v7

**Comment by wooorm** [comment]
This is a warning, and something no longer happening in the latest react (or are you sure you’re on the latest react version?)

Related to https://github.com/remarkjs/remark-react/commit/780b4cd3648442c611b5c39426717baf4f285dcf

**Comment by Ognian** [comment]
@wooorm I am on the lates react version 16.8.6, warnings still come (even with 16.9.0alpha0).
You are right that it is related to the above mentioned commit. Using the latest version where the patch is contained, which is 4.0.3, everything works correct, BUT starting with 5.0.0 where you reverted the patch it produces the warnings. These warnings are NOT harmless, do not forget that although we think in terms of tags (html tags), in react actually these are function calls; therefore I would suggest to reinsert this patch.

**Comment by wooorm** [comment]
We previously had this functionality, and tests for it, before React moved to semver-stable.
Since 16, the warning is no longer produced by the tests if the patch isn’t there, so it’s removed.

Could you work on a test case that shows the warning is produced?
P.S. Your codesandbox at `zz9wo4jv93`, which uses this library, does not produce warnings. `v30px4q3v7` does, but it uses [rehype-react](https://github.com/rhysd/rehype-react)

> These warnings are NOT harmless, do not forget that although we think in terms of tags (html tags), in react actually these are function calls; therefore I would suggest to reinsert this patch.

I’m aware of how virtual DOMs work.

**Comment by Ognian** [comment]
@wooorm https://codesandbox.io/s/zz9wo4jv93 produces the same warnings when on 5.0.1 and no such warnings when on 4.0.3 At the moment it is on 5.0.1 after my last post it was on 4.0.3. Everything is reproducible with the codebox.
My apologies  for my last comment, it was not intended the way you understood.
Ognian

**Comment by wooorm** [comment]
Hmm, I have no idea why the tests would not show the warning, but your code does. Any ideas? Reason I’m asking: I’d like to include tests for changes, so it’s important to me to know what we’re fixing.

> My apologies for my last comment, it was not intended the way you understood.

Ah good, thanks for the apology, and I I get it: it’s easy to get misunderstood on the internet!

**Comment by Ognian** [comment]
@wooorm your tests use `React.renderToStaticMarkup` [here](https://github.com/facebook/react/blob/master/packages/react-dom/src/server/ReactDOMStringRenderer.js#L30) but when not using server side rendering `ReactDOM.render` [probably here](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOM.js#L672) is used. Only this is enough to produce quite different behaviour...
I think that your tests are pretty correct the way they are. I would just keep in mind that they can not simulate such real world problems...

**Comment by wooorm** [comment]
Alright, I think we need to add it back. Can you work on a PR, and assert that it works?

**Comment by Box33Net** [comment]
I was having a similar issue and google brought me here, so just going to drop my solution here.

In my case I needed to install `remark-gfm` in order to get my table to resolve properly.

I found the fix from this blogpost:
https://unifiedjs.com/learn/recipe/remark-table/


Old Code:
```
  // Use remark to convert markdown into HTML string
  const processedContent = await remark()
    .use(html)
    .process(matterResult.content);
  const contentHtml = processedContent.toString();
```

New Code (After Installing remark-gfm):
```
  // Use remark to convert markdown into HTML string
  const processedContent = await remark()
    .use(html)
    .use(remarkGfm) // Added this line
    .process(matterResult.content);
  const contentHtml = processedContent.toString();
```

**Comment by BrendanSluke** [comment]
I was having a similar issue and google brought me here, so just going to drop my solution here.

In my case I needed to install `remark-gfm` in order to get my table to resolve properly.

I found the fix from this blogpost:
https://unifiedjs.com/learn/recipe/remark-table/


Old Code:
```typescript
import matter from "gray-matter";
import { remark } from "remark";
import html from "remark-html";

// Use remark to convert markdown into HTML string
const processedContent = await remark()
  .use(html)
  .process(matterResult.content);
const contentHtml = processedContent.toString();
```

New Code (After Installing remark-gfm):
```typescript
import matter from "gray-matter";
import { remark } from "remark";
import remarkGfm from "remark-gfm"; // New Import!
import html from "remark-html";

// Use remark to convert markdown into HTML string
const processedContent = await remark()
  .use(html)
  .use(remarkGfm) // Added this line!
  .process(matterResult.content);
const contentHtml = processedContent.toString();
```
