### ISSUE TITLE
Nested ordered lists need at least 3 spaces to work

### ISSUE THREAD

**Issue by heauton** [mapbox/mdast-react#65]
### Subject of the issue

Nested ordered lists need at least 3 spaces to work while unordered lists require 2 spaces - which seems inconsistent. I am not sure if this is expected behavior. Is there a way to configure a number of spaces to make nesting work?

### Your environment

*   **Packages**: 6.0.0

### Steps to reproduce

Pasting this code in the example site:

```
- list
  - sublist with 2 spaces

---

1. list
  1. sublist with 2 spaces

---

1. list
   1. sublist with 3 spaces
```

Yields:

<img width="534" alt="Screenshot of Google Chrome (02-12-2019, 00-50-23)" src="https://user-images.githubusercontent.com/29621109/69916380-be19bc00-149d-11ea-950c-9084ecfb2f64.png">

### Expected behavior

Indenting with 2 spaces should make an ordered list nested -- just like an unordered list

### Actual behavior

Ignores indentation.

**Comment by wooorm** [comment]
Thanks for the detailed issue! This is in accordance with [commonmark](https://spec.commonmark.org/0.29/#example-225) though. You may be able to turn it off by setting [`commonmark: false` and `pedantic: true`](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#processoruseparse-options), but I suggest using more spaces instead!
