### ISSUE TITLE
Confusing readme

### ISSUE THREAD

**Issue by dowi** [mapbox/mdast-react#67]
Hi
This is not a bug but a problem with the readme instructions:

The readme example is
`unified()
              .use(parse)
              .use(remark2react)
              .processSync(this.state.text).result`

But later it says the API is 
`remark().use(react[, options])`

Can you please explain ? 
Thanks!

**Comment by ChristianMurphy** [comment]
duplicate of https://spectrum.chat/unified/remark/using-remark-react~1f62feee-87c2-463d-b333-f3796ec69e0c please see the answer there
