### ISSUE TITLE
remarkReactComponents not working

### ISSUE THREAD

**Issue by ricardomatias** [mapbox/mdast-react#68]
### remarkReactComponents not working

I have the following markdown and component. The image tag is discarded from the final result (htmlContent).

```md
<img src="/foo.png" id="logo" />
Lorem ipsum
```

```js
export const MarkdownContent = ({ content, ...props }) => {
	const opts = {
		createElement: React.createElement,
		schema: false,
		remarkReactComponents: {
			img: (props) => {
				console.log(props);
				return (<MarkdownImage {...props} />);
			},
		}
	};

	const htmlContent = unified()
		.use(parse)
		.use(remark2react, opts)
		.processSync(content).result;

	return (
		<div className="w-full p-8 bg-white sm:py-12 text-gray-800">
			<div className="container my-20 flex md:w-2/3 mx-auto flex-col">
				<div className={styles['markdown-content']}>
					{ htmlContent }
				</div>
			</div>
		</div>
	);
};
```

### Your environment

*   **OS**: Ubuntu
*   **Packages**: 7.0.1

**Comment by wooorm** [comment]
HTML in markdown is not supported, because it is dangerous.

Use remark-rehype, rehype-raw, and then rehype-react if you want a full blown HTML parser.
Alternatively, see <https://github.com/ChristianMurphy/react-remark>.

**Comment by ncrmro** [comment]
@wooorm just curious why we can get an empty img tag but remarkReactComponents wont even pass the url so that I can just define my own component?
