### ISSUE TITLE
Access the data property of hast code elements in my custom component

### ISSUE THREAD

**Issue by vstirbu** [mapbox/mdast-react#70]
### Subject of the feature

I want to customise the rendering of `code` elements based on metadata extracted from the markdown input.

### Problem

The metadata that exists in the mdast `code` nodes is added to as data to the hast by the default [mdast-util-to-hast handler](https://github.com/syntax-tree/mdast-util-to-hast/blob/main/lib/handlers/code.js#L22). However, that property gets lost and does not reach the custom renderer provided in the `remarkReactComponents`.

### Expected behavior

I want to access the metadata in the custom component:

```js
remarkReactComponents: {
  code: () => {
    // access the data here
  }
}
```

### Alternatives

Create alternative handlers for converting mdast to hast and pass them as options to toHast option. The handler will attach the matadata to the props using the same pattern as with [className](https://github.com/syntax-tree/mdast-util-to-hast/blob/main/lib/handlers/code.js#L15-L17)

```js
toHast: {
  handlers: {
    code: (h, node) => {
      // my handler
    }
  }
}
```

**Comment by wooorm** [comment]
Heya!

There are several ways to go about this.

First, this plugin is slated to be archived: https://github.com/unifiedjs/unified/issues/121. It’s been in the readme for quite a while that `rehype-react` is preferred. You could use [`passNode`](https://github.com/rehypejs/rehype-react#optionspassnode) there to pass `node` to all components.

Second, and my preferred method, would be these steps: https://github.com/wooorm/xdm#syntax-highlighting-with-the-meta-field. That’s for MDX, but it works here as well.
